spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]': # Apply to all routes
            allowedOrigins: "http://localhost:5173" # Allow this origin
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "Content-Type"
              - "Authorization"
            allowCredentials: true # Allow cookies/credentials

server:
  port: 8080

